name: Ejecutar pruebas MercadoLibre Automation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Configurar Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Ver versión de Chrome
        run: chrome --version

      - name: Ejecutar pruebas Maven (CI)
        run: mvn clean verify -Denvironment=ci
